---
- name: Deploy Docker Image to Dev Environment
  hosts: dev_servers
  become: yes  

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: belwalrohit642/spring3hibernate:29
        source: pull

    - name: Run Docker Container
      docker_container:
        name: spring3hibernate_dev
        image: belwalrohit642/spring3hibernate:29
        state: started
        ports:
          - "8080:8080" 
